spring:
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: perform
  data:
    redis:
      port: 6380
      host: localhost
  datasource:
    hikari:
      maximum-pool-size: 20       # 커넥션 풀 크기
      minimum-idle: 5
      max-lifetime: 600000       # 10분으로 줄임 (ms)
      idle-timeout: 300000       # 5분
      connection-timeout: 30000  # 30초
    url: jdbc:mysql://localhost:3307/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: myuser
    password: user-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: false
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    secret: ${KAKAO_CLIENT_SECRET}

  naver:
    client-id: ${NAVER_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/naver/callback
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    client-secret: ${NAVER_CLIENT_SECRET}

payment:
  toss:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_SECRET_KEY}
    confirm-url: /v1/payments/confirm