spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: yeon
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false

payment:
  toss:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_SECRET_KEY}
    confirm-url: /v1/payments/confirm

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    secret: ${KAKAO_CLIENT_SECRET}

  naver:
    client-id: ${NAVER_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/naver/callback
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
    client-secret: ${NAVER_CLIENT_SECRET}


jwt:
  secret-key: ${JWT_SECRET_KEY}
  accessToken-expiration-millis: 1000000 # 추후 수정

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    region: ${S3_REGION}
    access-key-id: ${S3_ACCESS_KEY}
    secret-access-key: ${S3_SECRET_KEY}

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
  metrics:
    enable:
      jdbc: true
    tags:
      application: yeon